/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package npcdesktop;

/**
 *
 * @author Admin
 */
public class RightPanelWithSelectCharacter extends javax.swing.JPanel {

    /**
     * Creates new form RightPanelWithSelectCharacter
     */
    public RightPanelWithSelectCharacter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanel = new javax.swing.JPanel();
        buttonPanel4 = new javax.swing.JPanel();
        sexLabel3 = new javax.swing.JLabel();
        nameBox3 = new javax.swing.JComboBox<>();
        raceLabel3 = new javax.swing.JLabel();
        raceBox3 = new javax.swing.JComboBox<>();
        subraceBox3 = new javax.swing.JComboBox<>();
        classBox3 = new javax.swing.JComboBox<>();
        alingmentBox3 = new javax.swing.JComboBox<>();
        subraceLabel3 = new javax.swing.JLabel();
        classLabel3 = new javax.swing.JLabel();
        alingmentLabel3 = new javax.swing.JLabel();
        ageBox3 = new javax.swing.JComboBox<>();
        ageLabel3 = new javax.swing.JLabel();
        selectButton3 = new javax.swing.JButton();
        resetButton3 = new javax.swing.JButton();
        buttonPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        rightPanel.setBackground(new java.awt.Color(153, 224, 248));

        buttonPanel4.setBackground(new java.awt.Color(0, 153, 153));
        buttonPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Wybierz postać"));
        buttonPanel4.setOpaque(false);

        sexLabel3.setText("Imię");

        nameBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        raceLabel3.setText("Rasa");

        raceBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subraceBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        classBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        alingmentBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subraceLabel3.setText("Podrasa");

        classLabel3.setText("Klasa");

        alingmentLabel3.setText("Charakter");

        ageBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ageLabel3.setText("Wiek");

        selectButton3.setText("Wybierz");

        resetButton3.setText("Resetuj");

        javax.swing.GroupLayout buttonPanel4Layout = new javax.swing.GroupLayout(buttonPanel4);
        buttonPanel4.setLayout(buttonPanel4Layout);
        buttonPanel4Layout.setHorizontalGroup(
            buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanel4Layout.createSequentialGroup()
                        .addComponent(selectButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(buttonPanel4Layout.createSequentialGroup()
                        .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(raceLabel3)
                            .addComponent(subraceLabel3)
                            .addComponent(classLabel3)
                            .addComponent(alingmentLabel3)
                            .addComponent(ageLabel3)
                            .addComponent(sexLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonPanel4Layout.createSequentialGroup()
                                .addComponent(nameBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel4Layout.createSequentialGroup()
                                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(subraceBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(raceBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel4Layout.createSequentialGroup()
                                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alingmentBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(classBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ageBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        buttonPanel4Layout.setVerticalGroup(
            buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raceBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subraceBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subraceLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alingmentBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alingmentLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel3))
                .addGap(30, 30, 30)
                .addGroup(buttonPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectButton3)
                    .addComponent(resetButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        buttonPanel1.setBackground(new java.awt.Color(0, 153, 153));
        buttonPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));
        buttonPanel1.setOpaque(false);

        backButton.setText("Wróć");
        backButton.setActionCommand("");

        closeButton.setText("Zamknij");

        javax.swing.GroupLayout buttonPanel1Layout = new javax.swing.GroupLayout(buttonPanel1);
        buttonPanel1.setLayout(buttonPanel1Layout);
        buttonPanel1Layout.setHorizontalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonPanel1Layout.setVerticalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(closeButton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(buttonPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        buttonPanel4.getAccessibleContext().setAccessibleParent(this);
        buttonPanel1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ageBox;
    private javax.swing.JComboBox<String> ageBox1;
    private javax.swing.JComboBox<String> ageBox2;
    private javax.swing.JComboBox<String> ageBox3;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel ageLabel2;
    private javax.swing.JLabel ageLabel3;
    private javax.swing.JComboBox<String> alingmentBox;
    private javax.swing.JComboBox<String> alingmentBox1;
    private javax.swing.JComboBox<String> alingmentBox2;
    private javax.swing.JComboBox<String> alingmentBox3;
    private javax.swing.JLabel alingmentLabel;
    private javax.swing.JLabel alingmentLabel1;
    private javax.swing.JLabel alingmentLabel2;
    private javax.swing.JLabel alingmentLabel3;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JPanel buttonPanel4;
    private javax.swing.JComboBox<String> classBox;
    private javax.swing.JComboBox<String> classBox1;
    private javax.swing.JComboBox<String> classBox2;
    private javax.swing.JComboBox<String> classBox3;
    private javax.swing.JLabel classLabel;
    private javax.swing.JLabel classLabel1;
    private javax.swing.JLabel classLabel2;
    private javax.swing.JLabel classLabel3;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> nameBox;
    private javax.swing.JComboBox<String> nameBox1;
    private javax.swing.JComboBox<String> nameBox2;
    private javax.swing.JComboBox<String> nameBox3;
    private javax.swing.JComboBox<String> raceBox;
    private javax.swing.JComboBox<String> raceBox1;
    private javax.swing.JComboBox<String> raceBox2;
    private javax.swing.JComboBox<String> raceBox3;
    private javax.swing.JLabel raceLabel;
    private javax.swing.JLabel raceLabel1;
    private javax.swing.JLabel raceLabel2;
    private javax.swing.JLabel raceLabel3;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton resetButton3;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton selectButton1;
    private javax.swing.JButton selectButton2;
    private javax.swing.JButton selectButton3;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel sexLabel1;
    private javax.swing.JLabel sexLabel2;
    private javax.swing.JLabel sexLabel3;
    private javax.swing.JComboBox<String> subraceBox;
    private javax.swing.JComboBox<String> subraceBox1;
    private javax.swing.JComboBox<String> subraceBox2;
    private javax.swing.JComboBox<String> subraceBox3;
    private javax.swing.JLabel subraceLabel;
    private javax.swing.JLabel subraceLabel1;
    private javax.swing.JLabel subraceLabel2;
    private javax.swing.JLabel subraceLabel3;
    // End of variables declaration//GEN-END:variables
}
