
package npcdesktop;

import java.sql.ResultSet;
import static mssql.Mssql.connection;
import static mssql.Mssql.getData;


public class selectButtonPanel extends javax.swing.JPanel {

    /**
     * Creates new form selectButtonPanel
     */
    public selectButtonPanel() {
        initComponents();
        fillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameBox = new javax.swing.JComboBox<>();
        raceLabel1 = new javax.swing.JLabel();
        raceBox1 = new javax.swing.JComboBox<>();
        classBox1 = new javax.swing.JComboBox<>();
        classLabel1 = new javax.swing.JLabel();
        selectButton1 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        buttonPanel1.setBackground(new java.awt.Color(0, 153, 153));
        buttonPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wybierz postać"));
        buttonPanel1.setOpaque(false);

        nameLabel.setText("Imię");

        nameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        raceLabel1.setText("Rasa");

        raceBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        classBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        classLabel1.setText("Klasa");

        selectButton1.setText("Wybierz");
        selectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButton1ActionPerformed(evt);
            }
        });

        resetButton2.setText("Resetuj");

        javax.swing.GroupLayout buttonPanel1Layout = new javax.swing.GroupLayout(buttonPanel1);
        buttonPanel1.setLayout(buttonPanel1Layout);
        buttonPanel1Layout.setHorizontalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanel1Layout.createSequentialGroup()
                        .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(buttonPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(resetButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(buttonPanel1Layout.createSequentialGroup()
                        .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(buttonPanel1Layout.createSequentialGroup()
                                .addComponent(classLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(classBox1, 0, 179, Short.MAX_VALUE))
                            .addGroup(buttonPanel1Layout.createSequentialGroup()
                                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(raceLabel1)
                                    .addComponent(nameLabel))
                                .addGap(34, 34, 34)
                                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameBox, 0, 179, Short.MAX_VALUE)
                                    .addComponent(raceBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        buttonPanel1Layout.setVerticalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raceLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classLabel1))
                .addGap(40, 40, 40)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectButton1)
                    .addComponent(resetButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButton1ActionPerformed
        // TODO add your handling code here:
        Home.rightPanel.setVisible(false);
        Home.imageLabel.setVisible(false);
        Home.characterSheetPanel1.setVisible(false);
        Home.rightPanelToSelectCharacter2.setVisible(true);
        Home.characterListsPanel.setVisible(true);

    }//GEN-LAST:event_selectButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JComboBox<String> classBox1;
    private javax.swing.JLabel classLabel1;
    private javax.swing.JComboBox<String> nameBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> raceBox1;
    private javax.swing.JLabel raceLabel1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton selectButton1;
    // End of variables declaration//GEN-END:variables

    private String random = "Random";
    private String[] columns = {"imie", "rasa", "podrasa", "klasa", "charakter", "wiek"};
    private String table = "Postac";
    //private JComboBox[] comboList = {sexBox, raceBox, subraceBox, classBox, alingmentBox, ageBox};
    
    //wypelnienie listy typu JComboBox danymi produktow
    private void fillCombo() {
  
    try {
        //name 
        String sqlQuery = String.format("SELECT %s FROM %s", columns[0], table);
        ResultSet resultSet = getData(sqlQuery);
        nameBox.removeAllItems();
        nameBox.addItem(random);
        while(resultSet.next()) {
            String  s = resultSet.getString(columns[0]);
            nameBox.addItem(s);
        }
        //race
        sqlQuery = String.format("SELECT %s FROM %s", columns[1], table);
        resultSet = getData(sqlQuery);
        raceBox1.removeAllItems();
        raceBox1.addItem(random);
        while(resultSet.next()) {
            String  s = resultSet.getString(columns[1]);
            raceBox1.addItem(s);
        }
        //classes
        sqlQuery = String.format("SELECT %s FROM %s", columns[3], table);
        resultSet = getData(sqlQuery);
        classBox1.removeAllItems();
        classBox1.addItem(random);
        while(resultSet.next()) {
            String  s = resultSet.getString(columns[3]);
            classBox1.addItem(s);
        }
        connection.close();
        
    } catch (Exception e) {
        //Gdyby coś poszło nie tak, wydrukuj komunikat...
        System.out.println(e.getMessage());
    }
    
    }
}
