--ustawienie bazy danych
USE [NPC]
GO

--tabela Atrybuty

INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (9, 20, 19, 15, 12, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (16, 9, 14, 17, 19, 17) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (12, 19, 19, 8, 12, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 14, 20, 20, 20, 17) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (10, 12, 15, 12, 12, 19) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 8, 10, 18, 13, 17) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (17, 12, 14, 12, 15, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (12, 11, 16, 14, 9, 9) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15, 18, 9, 14, 9, 12) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (17, 18, 17, 16, 8, 16) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (8, 10, 14, 8, 16, 9) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (9, 14, 8, 18, 11, 15) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18, 14, 11, 9, 13, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (14, 9, 10, 17, 13, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (14, 11, 8, 15, 19, 14) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (12, 12, 14, 10, 9, 12) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (9, 9, 20, 19, 11, 17) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 14, 14, 14, 10, 18) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 11, 12, 17, 15, 15) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (10, 11, 9, 14, 10, 18) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (8, 8, 16, 16, 10, 20) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 8, 8, 13, 18, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 10, 12, 18, 9, 10) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 12, 11, 11, 17, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 13, 12, 15, 17, 18) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (8, 9, 15, 20, 15, 10) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (19, 18, 18, 10, 16, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (17, 14, 13, 17, 9, 19) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (12, 13, 16, 13, 8, 9) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18, 11, 19, 19, 9, 14) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (17, 13, 11, 13, 15, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (20, 11, 12, 10, 20, 14) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 15, 8, 11, 17, 14) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15, 20, 9, 14, 14, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11, 9, 12, 15, 11, 15) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 12, 17, 17, 13, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (8, 19, 12, 17, 19, 20) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (8, 12, 13, 18, 13, 9) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18, 16, 16, 14, 16, 12) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15, 8, 10, 15, 12, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15, 8, 8, 19, 20, 13) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (20, 10, 20, 19, 12, 8) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 16, 15, 20, 16, 11) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18, 20, 10, 19, 8, 16) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (14, 17, 9, 16, 18, 10) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (9, 8, 11, 15, 18, 18) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (10, 15, 12, 18, 13, 19) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15, 11, 14, 14, 13, 17) 
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (13, 9, 16, 18, 15, 11) 
