--ustawienie bazy danych
USE [NPC]
GO

--tabela Plec
GO
INSERT [dbo].[Plec] ([plec]) VALUES (N'Kobieta')
INSERT [dbo].[Plec] ([plec]) VALUES (N'Mężczyzna')

--tabela Wiek
INSERT [dbo].[Wiek] ([wiek]) VALUES (N'Dziecko')
INSERT [dbo].[Wiek] ([wiek]) VALUES (N'Młody dorosły')
INSERT [dbo].[Wiek] ([wiek]) VALUES (N'Dorosły')
INSERT [dbo].[Wiek] ([wiek]) VALUES (N'Stary')

--tabela Bonus ????
-- +1
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie wszystkich cech o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Siły o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Zręczności o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Kondycji o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Inteligencji o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Mądrości o 1',1)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (1, N'Zwiększenie Charyzmy o 1',1)
-- +2
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Siły o 2',2)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Zręczności o 2',2)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Kondycji o 2',2)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Inteligencji o 2',2)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Mądrości o 2',2)
INSERT [dbo].[Bonus] ([bonus], [opis], [bonusValue]) VALUES (2, N'Zwiększenie Charyzmy o 2',2)

SELECT @@IDENTITY

--tabela Rasa 
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Człowiek', 1 ) 
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Elf',9) 
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Krasnolud', 10 )
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Niziołek',9 )
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Diabelstwo',5)
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Drakon', 8 )
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Gnom',11)
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Półelf',13)
INSERT [dbo].[Rasa] ([rasa], [bonusID]) VALUES (N'Półork',8  )

--tabela Podrasa   
--elfy
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Leśny',2,6)
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Wysoki',2,5)
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Mroczny',2,7)
--krasnoludy
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Górski',3,8)
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Wzgórzowy',3,6)
--niziołki
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Hardy',4,4)
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Lekkostopy',4,7)
--gnomy
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Leśny',7,4)
INSERT [dbo].[Podrasa] ([podrasa], [rasaID], [bonusID]) VALUES (N'Skalny',7,4)

--tabela Klasa
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Barbarzyńca',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Bard',3)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Czarownik',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Druid',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Kleryk',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Łotr',4)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Łowca',3)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Mag',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Mnich',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Paladyn',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Wojownik',2)
INSERT [dbo].[Klasa] ([klasa], [iloscUm]) VALUES (N'Zaklinacz',2)


--tabela Charakter
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Praworządny dobry') 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Neutralny dobry') 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Chaotyczny dobry' ) 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Praworządny neutralny' ) 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Neutralny') 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Chaotyczny neutralny' ) 
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Praworządny zły')
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Neutralny zły' )
INSERT [dbo].[Charakter] ([charakter]) VALUES (N'Chaotyczny zły' )

--tabela Charakter_Rasy
	--ludzie
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,1 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (2,1 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (3,1 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (4,1 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (5,1 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (6,1)
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (7,1 )
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (8,1 )
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (9,1 )
	--elfy
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,2 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (2,2 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (3,2 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (4,2 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (6,2 ) 
	--krasnoludy
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,3 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (4,3 )
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (7,3) 
	--niziołki
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,4 )
	--diabły
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (6,5 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (7,5) 
	--drakoni
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,6 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (3,6 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (7,6) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (9,6 )
	--gnomy
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (1,7 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (2,7 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (3,7 ) 
	--półelfy
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (3,8 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (6,8 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (9,8 )
	--półorki
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (6,9 ) 
INSERT [dbo].[Charakter_Rasy] ([charakterID], [rasaID]) VALUES (9,9 )

--tabela Charakter_Klasy
	--barbarzyńca
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (6,1 )
	--bard
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (6,2 ) 
	--druid
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (5,4 ) 
	--mag
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (4,8 )
	--mnich
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (4,9 )
	--łotr
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (6,6 )
	--paladyn
INSERT [dbo].[Charakter_Klasy] ([charakterID], [klasaID]) VALUES (1, 10 ) 

--tabela Umiejetnosci
--klasa 1-18
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Akrobatyka')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Atletyka')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Historia')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Intuicja')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Medycyna')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Opieka nad zwierzętami')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Oszustwo')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Percepcja')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Perswazja')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Przyroda')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Religia')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Skradanie się')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Sztuka przetrwania')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Śledztwo')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wiedza tajemna')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Występy')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Zastraszanie')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Zwinne dłonie')
--rasa
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Brutalne ataki')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Diabelska spuźnizna')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Dodatkowy język')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Elfia szkoła walki')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Gnomi spryt')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Groźny')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Krasnoludzka odporność')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Krasnoludzki trening bojowy')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Krasnoludzki trening zbrojny')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Krasnoludzka wytrzymałość')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Magia drowów')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Magiczna sztuczka')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Majsterkowicz')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Maska dziczy')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Mądrość wynalazcy')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Mowa małych zwierząt')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Niezauważalny')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Odporność na obrażenia')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Odporny na trucizny')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Odwaga')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Piekielna odporność')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Smoczy rodowód') --tabelka do losowania?
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Szczęście')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Szkoła walki drowów')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Szybki')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Rodowód Fay')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Trans')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Urodzony iluzjonista')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wiedza o kamieniu')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Widzenie w ciemności')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wola życia')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wrażliwość na światło słoneczne')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wszechstronność')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wyjątkowe widzenie w ciemności')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Wyostrzone zmysły')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Zionięcie')
INSERT [dbo].[Umiejetnosci] ([umiejetnosc] ) VALUES (N'Zwinność niziołka')


--tabela Umiejetności_Rasa
--elfy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (53,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (44,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (45,2)
--leśne
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (22,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (43,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (32,2)
--wysokie
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (30,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (21,2)
--mroczne
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (52,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (50,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (29,2)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (42,2)
--krasnoludy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,3)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (25,3)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (26,3)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (47,3)
--górski
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (27,3)
--wzgórzowy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (28,3)
--Niziołki
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (41,4)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (38,4)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (55,4)
--hardy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (37,4)
--lekkostopy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (35,4)
--diabelstwo
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,5)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (39,5)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (20,5)
--drakon
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (40,6) --tabelka do losowania?
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (54,6)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (36,6)
--gnom
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,7)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (23,7)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,7)
--leśny
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (46,7)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (34,7)
--skalny
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (33,7)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (31,7)
--półelfy
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,8)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (44,8)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (51,8)
--półorki
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (48,9)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (24,9)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (49,9)
INSERT [dbo].[Umiejetnosci_Rasa] ([umiejetnoscID], [rasaID]) VALUES (19,9)

--tabela Umiejetności_Podrasa
--leśne
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (22,1)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (43,1)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (32,1)
--wysokie
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (30,2)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (21,2)
--mroczne
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (52,3)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (50,3)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (29,3)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (42,3)
--górski
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (27,4)
--wzgórzowy
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (28,5)
--hardy
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (37,6)
--lekkostopy
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (35,7)
--leśny
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (46,8)
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (34,8)
--skalny
INSERT [dbo].[Umiejetnosci_Podrasa] ([umiejetnoscID], [podrasaID]) VALUES (33,9)


--tabela Umiejetnosci_Podrasa_Klasa
	--barbarzyńca
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,1)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (6,1)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (10,1)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (13,1)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,1)
	--bard
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (1,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (5,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (6,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (7,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (8,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (9,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (10,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (12,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (13,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (14,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (15,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (16,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,2)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (18,2)
	--czarownik
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (7,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (10,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (14,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (15,3)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,3)
	--druid
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (5,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (6,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (8,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (10,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (13,4)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (15,4)
	--kleryk
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,5)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,5)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (5,5)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (9,5)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,5)
	--łotr
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (1,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (7,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (8,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (9,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (12,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (14,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (16,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,6)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (18,6)
	--łowca
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (6,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (8,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (10,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (12,7)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (13,7)
	--mag
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,8)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,8)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (5,8)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,8)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (14,8)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (15,8)
	--mnich
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (1,9)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,9)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,9)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,9)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,9)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (12,9)
	--paladyn
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,10)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,10)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (5,10)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (9,10)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,10)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,10)
	--wojownik
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (1,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (2,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (3,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (6,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (8,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (13,11)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,11)
	--zaklinacz
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (4,12)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (7,12)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (9,12)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (11,12)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (15,12)
INSERT [dbo].[Umiejetnosci_Klasa] ([umiejetnoscID], [klasaID] ) VALUES (17,12)


--tabela Imiona
--ludzkie
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Darwin', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Dorn', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Evendur', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gorstag', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Grim', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Helm', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Malark', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Randal', 1, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Stedd', 1, 2)
	--kobiecie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Arveene', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Esvele', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jhessail', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kerri', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lureene', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Miri', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rowan', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shandri', 1, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Tessele', 1, 1)
--elfie
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Adran', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Aeler', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Aramil', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Arannis', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Aust', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Beiro', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Berrian', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Carric', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Enialis', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Erdan', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Erevan', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Galinndan', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Haradai', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Heian', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Himo', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Immeral', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ivellios', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Laucian', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mindartis', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Paelias', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Peren', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Qarion', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Riardon', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rolen', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Soveliss', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thamior', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Tharivol', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Theran', 2, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Varis', 2, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Adrie', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Althaea', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Anastrianna', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Andraste', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Antinua', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bethrynna', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Birel', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Caelynn', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Drusilia', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Enna', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Felosial', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ielenia', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jelenneth', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Keyleth', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Leshanna', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lia', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Meriele', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mialee', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Naivara', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Quelenna', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Quiathe', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Sariel', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shanairra', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shava', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Silaqui', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Theirastra', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thia', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Vadania', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Valanthe', 2, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Xanaphia', 2, 1)
--krasnoludzkie
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Adrik', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Alberich', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Baern', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Barendd', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Brottor', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bruenor', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Dain', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Darrak', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Delg', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Eberk', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Einkil', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Fargrim', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Flint', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gardain', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Harbek', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kildrak', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Morgran', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Orsik', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Oskar', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rangrim', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rurik', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Taklinn', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thoradin', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thorin', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Tordek', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Traubon', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Travok', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ulfgar', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Veit', 3, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Vondal', 3, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Amber', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Artin', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Audhil', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bardryn', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Dagnal', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Diesa', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Eldeth', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Falkrunn', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Finellen', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gunnloda', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gurdis', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Hejla', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Hlin', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kathra', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kristryd', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ilde', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Liftrasa', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mardred', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Riswynn', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Sanni', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Torbera', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Torgga', 3, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Vistra', 3, 1)
--niziołków
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Alton', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ander', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Cade', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Corrin', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Eldon', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Errich', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Finnan', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Garret', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lindal', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lyle', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Merric', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Milo', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Osborn', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Perrin', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Reed', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Roscoe', 4, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Welby', 4, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Andry', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bree', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Callie', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Cora', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Euphemia', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jillian', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kithri', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lavinia', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lidda', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Meria', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nedda', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Paela', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Portia', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Seraphina', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shaena', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Trym', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Vani', 4, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Verna', 4, 1)
--diabelstwo
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Akmenos', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ammon', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Barakas', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Damakos', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ekemon', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Iados', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kairon', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Leucis', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Melech', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mordai', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Morthos', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Pelaios', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Skamos', 5, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Therai', 5, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Akta', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Anakis', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bryseis', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Criella', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Damaia', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ea', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kallista', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lerissa', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Makaria', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nemeia', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Orianna', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Phelaia', 5, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rieta', 5, 1)
--drakon
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Arjhan', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Balasar', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bharash', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Donaar', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ghesh', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Heskan', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kriv', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Medrash', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mehen', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nadarr', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Pandjed', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Patrin', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rhogar', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shamash', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shedinn', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Tharhun', 6, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Torinn', 6, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Akra', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Biri', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Daar', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Farideh', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Harann', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Havilar', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jheri', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kava', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Korinn', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mishann', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nala', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Perra', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ralann', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Sora', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Surina', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thava', 6, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'uadjit', 6, 1)
--gnomie
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Alston', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Alvyn', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Boddynock', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Brocc', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Burgell', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Dimble', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Eidon', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Erky', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Fonkin', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Frug', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gerbo', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gimble', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Glim', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jebeddo', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kellen', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Namfodie', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Orryn', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Roondar', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Seebo', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Sindri', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Warryn', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Wrenn', 7, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Zook', 7, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bimpnottin', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Breena', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Caramip', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Carlin', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Donella', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Duvamil', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ella', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ellyjobell', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ellywick', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lilli', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Loopmottion', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Lorilla', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mardnab', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nissa', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Nyx', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Oda', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Orla', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Roywyn', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shamil', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Tana', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Waywocket', 7, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Zanna', 7, 1)
--półelfy
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Aoth', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Bareris', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kethorn', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mumed', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ramas', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thazar-de', 8, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Rimardo', 8, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Fyevarra', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Hulmarra', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mei', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Atala', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ceidil', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Jasmal', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Yasheida', 8, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Zasheida', 8, 1)
--półorki
	--męskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Dench', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Feng', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Gell', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Henk', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Holg', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Imsh', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Keth', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Krusk', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Mhurren', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ront', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shump', 9, 2)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Thokk', 9, 2)
	--żeńskie
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Baggi', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Emen', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Engong', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Kansif', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Myev', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Neega', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ovak', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Ownika', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Shautha', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Sutha', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Vola', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Volen', 9, 1)
INSERT [dbo].[Imiona] ([imie], [rasaID], [plecID]) VALUES (N'Yevelda', 9, 1)
	
--tabela Nazwiska
--ludzkie
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Amblecrown', 1)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Buckman', 1)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Dundragon', 1)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Evenwood', 1)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Greycastle', 1)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Tallstag', 1)
--elfie
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Amakir "Perłowy Kwiat"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Amastacia "Gwiezdny Kwiat"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Galanodel "Księżycowy Szept"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Holimion "Diamentowa Rosa"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ilphelkiir "Perłowy Rozkwit"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Liadon "Srebrny Liść"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Meliamne "Dębowa Pięta"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Nailo "Nocna Bryza"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Siannodel "Księżycowy Strumień"', 2)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Xiloscient "Złoty Poranek"', 2)
--krasnoludzkie
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Balderk', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Battlehammer', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Brawnanvil', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Dankil', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Fireforge', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Frostbeard', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Gorunn', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Holderhek', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ironfist', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Loderr', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ludgehr', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Rummanheim', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Strakeln', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Torunn', 3)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ungart', 3)
--niziołków
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Brushgather', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Goodbarrel', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Greenbottle', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'High-hill', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Hilltopple', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Leagallow', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Tealeaf', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Thorngage', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Tosscobble', 4)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Underbough', 4)
--diabelstwo
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Chwała', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Cierpienie', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Doskonałość', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ideał', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Kredo', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Losowość', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Muzyka', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Nadzieja', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Nigdzie', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Otwartość', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Padlina', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Poezja', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Poszukiwanie', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Rozpacz', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Strach', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Szacunek', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Sztuka', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Śpiew', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Znużenie', 5)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Zuchwałość', 5)
--drakon
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Clethtinthiallor', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Daardendrian', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Delmirev', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Drachendamdion', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Fenkenkabrandon', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Kepeshkmolik', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Kerrhylon', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Kimbatuul', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Linxakasendalor', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Myastan', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Nemmonis', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Norixius', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ophinshtalajiir', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Prexijandilin', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Shestendeliath', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Turnuroth', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Verhisathurgiesh', 6)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Yarjerit', 6)
--gnom
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Beren', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Daergel', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Folkor', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Garrick', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Nackle', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Murnig', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ningel', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Raulnor', 7)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Scheppen', 7)
--półelfy
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Dumein', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Ankhalab', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Brightwood', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Helder', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Hornraven', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Stormwind', 8)
INSERT [dbo].[Nazwiska] ([nazwisko], [rasaID]) VALUES (N'Windrivver', 8)
--półorki
	--brak nazwiska

--tabela Atrybuty
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (11,13,6,12,7,9)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (10,7,8,12,5,14)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15,6,11,13,14,7)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (16,13,16,15,10,14)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18,9,12,12,11,13)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (15,10,10,15,8,17)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (17,8,8,19,11,13)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (18,18,10,8,11,10)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (9,12,8,13,15,19)
INSERT [dbo].[Atrybuty] ([sila], [kondycja], [zrecznosc], [inteligencja], [madrosc], [charyzma]) VALUES (12,14,16,13,15,17)

--tabela Wygląd	
	--człowiek
	--dziecko

INSERT [dbo].[Wyglad] ([wyglad], [plecID], [rasaID], [podrasaID], [wiekID]) VALUES (N'Ma rumianą skórę i piwne oczy. Jej długie falowane rude włosy są związane w kucyk. Lubi bawić się w gry takie jak rzutki i zazwyczaj wygrywa',1,1,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma opaloną skórę, niebieskie oczy i krótkie jasnobrązowe włosy',2,1,NULL,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi mistyczne szaty i atmosferę egzotycznej tajemnicy. Ma jasną skórę i zielone oczy. Jej bardzo długie, kręcone, ciemnobrązowe włosy są stylizowane na misterne warkocze. Jest muskularna i dobrze umięśniona.',1,1,NULL,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi zwykłe, funkcjonalne ubrania robocze. Ma rumianą skórę i orzechowe oczy. Ma krótkie, kręcone, ciemnobrązowe włosy. Ma grube, ciemnobrązowe wąsy. Jest muskularny i szybki.',2,1,NULL,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi ładne ubrania. Ma opaloną skórę i orzechowe oczy. Jej bardzo długie, proste, czarne włosy są wiązane w kucyka. Jest silna, ale nieco krucha. ',1,1,NULL,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma na sobie proste chłopskie ubrania i trzyma ponadwymiarową, zakrzywioną laskę. Ma jasną skórę i niebieskie oczy. Jego ciemnobrązowe włosy są krótkie. Jest w całkiem dobrej formie.',2,1,NULL,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi brudny fatruch, pokryty odłamkami wosku. Ma bladą skórę i zielone oczy. Ma krótkie, proste, siwe włosy.',1,1,NULL,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bladą skórę i brązowe oczy. Jest kompletnie łysy. Jest leniwy i senny, ale zwodniczo silny',2,1,NULL,4)
		
	--elf
		--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ciemnozieloną skórę i brązowe oczy w kształcie migdałów. Jej długie, proste, jasnobrązowe włosy są wiązane w koński ogon. Nie jest zbyt silna, ale jest szybka.',1,2,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jasną skórę i złote migdałowe oczy. Jej falujące, niebieskie włosy są wiązane w bardzo długi warkocz. Jej rękawy są podwinięte, aby pokazać ręce.',1,2,2,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bladoczerwone migdałowe oczy. Jej faliste, białe włosy opadają za ramiona.',1,2,3,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jasnozieloną skórę i orzechowe oczy w kształcie migdałów. Ma średniej długości faliste miedziane włosy. Jest zwinny i szybki.',2,2,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma brązową skórę i złote migdałowe oczy, które mienią się jak gwiazdy. Ma średniej długości proste, jasnobrązowe włosy.',2,2,2,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bladoniebieskie oczy w kształcie migdałów. Boki jego głowy są ogolone, z paskiem prostych blond włosów po środku głowy.',2,2,3,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Opierając się na jej ubraniach, dodatkach i zachowaniu, można by się domyślić, że jest zbieraczką. Ma jasnozieloną skórę i brązowe migdałowe oczy. Jej faliste blond włosy opadają za ramiona.',1,2,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest ubrana w proste chłopskie ubrania i trzyma ponadwymiarową, zakrzywioną laskę. Ma miedzianą skórę i brązowe migdałowe oczy. Jej proste, niebieskie włosy są wiązane w długi warkocz. Jest drobna, ale wirująca i szybka.',1,2,2,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi zwykłe, funkcjonalne ubrania robocze. Ma bladoczerwone oczy. Jej bardzo długie, faliste, białe włosy są stylizowane na misterne warkocze. Jest bardzo wysoka i chuda. ',1,2,3,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Opierając się na jego ubraniach, dodatkach i zachowaniu, można by się domyślić, że jest myśliwym. Ma ciemnozieloną skórę i brązowe migdałowe oczy. Jego średniej długości falujące miedziane włosy są wiązane w koński ogon. Jest duży i twardy, i zawsze wydaje się czymś bawić.',2,2,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma na sobie podniszczone ubrania podróżne. Ma jasną skórę, brązowe oczy i średniej długości proste srebrne włosy. Jest zwinny, ale wygląda na chorego.',2,2,2,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma na sobie minimum ubrań i żelazny kołnierz na szyi. Ma bladoniebieskie, migdałowe oczy. Jego faliste, białe włosy opadają za ramiona. Lubi bawić się małymi przedmiotami, jak monety.',2,2,3,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Opierając się na jej ubraniach, dodatkach i zachowaniu, można by się domyślić, że jest myśliwym. Ma miedzianą skórę i zielone migdałowe oczy. Jej faliste, jasnobrązowe włosy są skręcone w wiele bardzo długich, ciasnych warkoczy. Jest dość silna.',1,2,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi wysokiej jakości ubrania robocze i kilka futer. Ma jasną skórę i zielone oczy w kolorze trawy. Jej faliste srebrne włosy opadają na ramiona. Jest w dobrej formie. Porusza się szybko i zwinnie. ',1,2,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi zwykłą, funkcjonalną odzież roboczą. Ma bladoniebieskie oczy w kształcie migdałów. Jej falujące blond włosy opadają za ramiona. Jest niezwykle wysoka. ',1,2,3,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma brązową skórę i orzechowe oczy w kształcie migdałów. Ma krótkie, kręcone, miedziane włosy. Jest dość zwinny.',2,2,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma na sobie skórzaną zbroję i sztylet na pasku. Ma jasną skórę i złote oczy w kształcie migdałów. Jego faliste, jasnobrązowe włosy opadają mu na ramiona. ',2,2,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Opierając się na jego ubraniach, dodatkach i zachowaniu, można by się domyślić, że jest on handlarzem żywym inwentarzem. Ma i bladoniebieskie, migdałowe oczy. Blond włosy opadają mu na ramiona. Jego prawe ramię jest w temblaku.',2,2,3,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi zwykłą, funkcjonalną odzież roboczą. Ma miedzianą skórę i brązowe oczy w kształcie migdałów. Jej cienkie, jasnobrązowe włosy opadają do pasa. Jej ręce są nerwowe, niespokojne i zajęte.',1,2,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma skórę z kości słoniowej i orzechowe oczy w kształcie migdałów. Faliste, niebieskie włosy opadają jej na ramiona. Ma poważne problemy z oddychaniem i musi cały czas łapać oddech.',1,2,2,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi proste chłopskie ubrania. Ma bladosrebrne, migdałowe oczy. Jej proste blond włosy są wiązane w krótki warkocz. Łatwo ją zaskoczyć przez co często podskakuje jak królik. ',1,2,3,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi zwykłą odzież roboczą i nienaciągnięty łuk. Ma miedzianą skórę i brązowe oczy. Jego falowane czarne włosy są skręcone w wiele bardzo długich, ciasnych warkoczy. Cierpi na przewlekłą, wyniszczającą chorobę.',2,2,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma na sobie dobrze skrojony strój podróżny. Ma miedzianą skórę i brązowe oczy. Jego proste blond włosy opadają na ramiona. Idąc lekko kuleje.',2,2,2,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bardzo długie, splecione, białe włosy i brązowe oczy. Ma miękką, czarną skórę. Jest w dobrej kondycji, ale nosi znamiona podeszłego wieku',2,2,3,4)
	--krasnoludy
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ciemnobrązową skórę i głęboko osadzone brązowe oczy. Ma krótkie, kręcone, rude włosy. Jest silna, ale niezdarna.',1,3,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma rumianą skórę i głęboko osadzone brązowe oczy. Jej bardzo długie kręcone ciemnobrązowe włosy są ozdobione wyszukanymi warkoczami.',1,3,2,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jasnobrązową skórę i szare oczy. Jego gęste, szare włosy są związane w prosty sposób. Nosi zielony, poplamiony kubrak',2,3,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest dość wysoki jak na krasnoluda. Ma jasnobrązowe oczy i ziemisty odcień skóry. Nosi kolczyk w uchu.',2,3,2,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest krępa i silna, a jej głos niesie się daleko kiedy mówi. Ma miedzane włosy i jasnoszare oczy. ',1,3,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma niebiesko-purpurowe oczy i ciemnobrązową skórę. Jej gęste, kręcone włosy zaplecione są w kilka grubych warkoczy.',1,3,2,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest bardzo niski i szeroki. Ma orzechowe oczy i pochmurny wyraz twarzy.',2,3,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma kruczoczarne włosy i niebieskie oczy. Ma bardzo krzaczaste brwi i niezgrabne dłonie.',2,3,2,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ogniste rude włosy, szare oczy i mnóstwo piegów na całym ciele. Nosi proste ubrania w kolorach ziemi.',1,3,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma atrakcyjną twarz i szerokie biodra. Jej kręcone włosy nie dają się zaplatać w warkocze.',1,3,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest krępy i silny. Ma wygolone włosy i gęstą, zaplecioną w warkocze brodę. Ma bardzo donośny głos.',2,3,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma głęboko osadzone ciemne oczy i miedziane włosy. Ma odstające uszy.',2,3,2,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jej długie, siwe włosy zaplecione są w mnóstwo warkoczy. Jest niziutka i wciąż bardzo żwawa.',1,3,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma purpurowe oczy i jasnobrązową skórę z lekkim odcieniem czerwieni. Rzadkie, miedziane włosy opadają jej na ramiona ',1,3,2,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ciemnobrązową skórę i orzechowe oczy. Białe włosy i broda zaplecione są w misterne warkocze z pierścieniami. Ma szramę na policzku i płaski nos.',2,3,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ziemisty odcień skóry i niebieskie oczy. Jest brzydki i przygarbiony.',2,3,2,4)
	--diabelstwo
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie, kręcone, srebrne włosy i białe oczy. Ma gładką, brązową skórę, krótko zawinięte rogi i cienki ogon z białą końcówką.',1,4,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma długie, kręcone białe włosy i czerwone oczy. Ma miękką, upiorną białą skórę i ładną twarz.',2,4,NULL,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma faliste srebrne włosy i złote oczy. Ma fioletową skórę i owalną, oszałamiającą twarz.',1,4,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma długie, proste, ogolone z prawej strony włosy i cyjanowe oczy. Ma szorstką czerwoną skórę i długie skręcone rogi.',2,4,NULL,1)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jedwabiście czerwoną skórę i srebrne oczy. Króciutkie różki wystają spomiędzy prostych purpurowych włosów.',1,4,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma włosy koloru jesiennych liści i czarne oczy. Ma fioletową skórę, okrągłą budowę ciała i lekko efektowną twarz.',2,4,NULL,1)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma długie, kruczoczarne włosy i czarne oczy. Rogi długie jak u gazeli zawijają się do tyłu.',1,4,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma proste, farbowane na czerwono włosy i złote oczy. Ma czekoladową skórę i chudą budowę ciała.',2,4,NULL,1)
	--drakon
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma matowe złote łuski i brązowe oczy. Wokół jej ust wystają gadzie wąsy.',1,5,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma metalowe łuski z brązu i brązowe oczy. Duże płetwiaste uszy wystają z boków jego głowy. Uwielbia pić z innymi pod stołem.',2,5,NULL,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma wyboistą głowę i zielone oczy. Ma szorstką niebieską łuskę.',1,5,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma wyboistą głowę i brązowe oczy. Ma chropowatą, czerwoną łuskę. Owalną twarz o wiecznie znudzonym grymasie.',2,5,NULL,1)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma głądką głowę i niebieskie oczy. Ma niebieską łuskę o lekko przybrudzonym odcieniu. Ma miękką, niezapomnianą twarz i lekko podłużne palce.',1,5,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ciemną falbankę dookołą głowy i szare oczy. Ma lśniącą, zielonąłuskę. Jest wysoki i ma muskularną budowę.',2,5,NULL,1)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma kościstą falbankę i szare oczy. Ma gładką, rdzawą łuskę, masywną budowę ale dziwnie atrakcyjną twarz.',1,5,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma gładką głowę i szare oczy. Wokół ust wyrastają mu gadzie wąsy. Ma szerokie, spiżowe łuski.',2,5,NULL,1)
	
	--gnom
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma śniadą cerę i roześmiane, szare oczy. Płowe włosy sterczą jej nieporządnie na wszystkie strony',1,6,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jej ozdobione haftami ubranie jest lekko przybrudzone. Ma blond włosy, szare oczy i lekko odstające uszy',1,6,2,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma opaloną skórę i brązowe oczy. Proste, brązowe włosy opadają mu na ramiona',2,6,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi luźne, kolorowe ubrania i buty z dużym szpicem. Ma niebieskie oczy i lekko zielonkawe włosy.',2,6,2,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest niska i drobna. Ma śniadą twarz z szerokim uśmiechem. Zielone oczy błyszczą żywym podekscytowaniem.',1,6,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bladoniebieskie oczy i jasnobrązową skórę. Szare, lekko rozwichrzone włosy opadają jej na ramiona. Wygląda na niespokojną i ciągle się wierci',1,6,2,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jego ciemne oczy giną pod krzaczastymi brwiami, a duży nos zasłania resztę twarzy. Jest szczupły i lekko utyka.',2,6,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jasnobrązowe oczy o kształcie migdałów i włosy w kolorze siana. Jest ubrany na myśliwską modłę, ale płaszcz jest obsypany drobnym haftem.',2,6,2,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma mizerną budowę ciałą. Ma jasną skórę, jasnoszare oczy i krótkie, blond włosy.',1,6,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma miedziane oczy w kształcie migdałów i lekko zielonkawe włosy. Jest ciągle uśmiechnięta i lubi bawić się drobnymi przedmiotami, jak np monety ',1,6,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma łysą głowę, czerwone oczy i ostre rysy twarzy. Ma szorstką, złotą skórę i muskularną budowę ciałą',2,6,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie, faliste, rude włosy i brązowe oczy.Ma żylastą, poparzoną słońcem, złocistą skórę i owalną, nijaką twarz',2,6,2,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie, przerzedzone szare włosy i pomarszczoną, różową skórę. Ma trójkątną twarz i wąskie usta.  ',1,6,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie, faliste złote włosy i złote oczy. Ma trójkątną, przeciętną twarz i regularną budowę ciała.',1,6,2,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma przycięte, faliste blond włosy i brązowe oczy. Ma niezapomnianą twarz',2,6,1,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma kręcone brązowe włosy i zielone oczy. Jego szorstka skóra jest ogorzała od wiatru. Jest powolny i często sprawia wrażenie zamyślonego.',2,6,2,4)

	--niziołek
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma którkie, kręcone rude włosy ogolone po prawej stronie i orzechowe oczy. Jasną, lekko złotawą skórę, podłużną twarz i lekką budowę. ',1,7,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma długie, piaskowe włosy zaplecione w warkocze i jasnoorzechowe oczy. Ma opaloną skórę i owalną, lekko pucułowatą twarz.',1,7,2,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma rumianą skórę i brązowe włosy. W okrągłej jego twarzy orzechowe włosy wyglądają jak mała paciorki. Jest niezgrabny i ma lekką nadwagę.',2,7,1,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma jasnobrązową skórę, pociągłą twarz i roześmiane oczy. Długie piaskowe włosy nosi związane w koński ogon.',2,7,2,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie farbowane na czarno włosy i brązowe oczy. Ma białą skórę, kanciastą twarz. Jest chuda i bardzo niezdarna.',1,7,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ubrana jest jak żebraczka. Ma faliste, złote włosy i niebieskie oczy. Jej twarz jest podłużna i niecodzienna. Łatwo traci oddech.',1,7,2,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma dość przystojną twarz, brązowe włosy i brązowe oczy. Jest regularnej budowy ciała, ale ma wyjątkowo mocne i silne dłonie',2,7,1,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bardzo długie, kręcone włosy i cyjanowe oczy. Kozia bródka przyciąga uwagę do twarzy.',2,7,2,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma przycięte brązowe włosy i brązowe oczy. Ma jasną skórę i trzy małe kolczyki na prawej brwi.',1,7,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma szarawy odcień skóry i głęboko osadzone brązowe oczy. Jej farbowane na pomarańczowo włosy są fantazyjnie upięte.',1,7,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest ogolony na łyso i ma bliznę na prawym ramieniu. Ma przykurzone ubranie i zupełnie przeciętną twarz.',2,7,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma miękką, nie rzucającą się w oczy twarz. Jest blondynem z ciemnobrązowymi oczami.',2,7,2,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest chuda i żylasta. Ma kwadratową, brzydką twarz. Bez przerwy pali fajkę i pachnie tytoniem.',1,7,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma siwe, kręcone włosy, pomarszczoną różową skórę i zielone oczy. Jest niższa niż stół w karczmie i ma ogrągłą, nijaką twarz.',1,7,2,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma szarą skórę, jest dość wysoki i ma podłużną, przerażającą twarz.',2,7,1,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma bardzo długie, blond włosy i złote oczy. Ma gładką, lekko opaloną skórę. Jego twarz jest kwadratowa z bardzo krótką brodą.',2,7,2,3)
	--półelfy
		--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótkie, bardzo bujne włosy i zielone oczy. Ma miękką, różową skórę i niewinną twarz. Na prawym ramieniu ma niedokończony tatuaż meduzy.',1,8,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma brudną, rudawą skórę i czarne oczy. Nosi farbowane na czarno włosy zaplecione w kilkanaście warkoczy. Jest średniego wzrostu i ma szczupłą budowę.',2,8,NULL,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma długie, białe włosy ogolone po lewej stronie i piwne oczy. Ma widmową, białą skórę i owalną, lekko fantazyjną twarz.',1,8,NULL,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma słomiane włosy, bardzo jasną skórę i błękitne oczy. Jest bardzo wysoki i nieprawdopodobnie chudy.',2,8,NULL,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma ciężkie, kasztanowe włosy i jasnoorzechowe oczy w kształcie migdałów. Ma lekko oliwkową skórę. Ubiera się strojnie',1,8,NULL,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Oceniając po ubraniu można by pomyśleć, że jest szlachcicem. Ma schludnie zaplecione ciemne włosy i prawie czarne oczy.',2,8,NULL,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest chuda i wydaje się bardzo krucha. Ma śnieżnobiałe włosy i piękną twarz z drobną pajęczyną zmarszczek.',1,8,NULL,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jego ciemne włosy przeplecione są pasmami siwizny. Ma intensywnie zielone oczy o wciąż intensywnym spojrzeniu.',2,8,NULL,4)
	
	--półorki
			--dziecko
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma szorstą, brudną szarą skórę i zielone oczy. Jej krótkie kły ledwie wystają z pomiędzy warg',1,9,NULL,1)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest niski i silny. Ma zielonkawy odcień skóry i szare oczy. Nosi naszyjniki pełne paciorków.',2,9,NULL,1)
		--młody dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi ubrania w żołnierskim stylu. Ma łysą głowę i niebieskie oczy. Jest topornej budowy i ma plemienny tatuaż na lewej nodze.',1,9,NULL,2)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest łysy, ma pochylone czoło i mocno wystające kły. Ciemne oczy łypią na wszystkich niechętnie.',2,9,NULL,2)
		--dorosły
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma gładką, szarawą skórę i ciemnobrązowe włosy. Jest wysoka i grubokoścista.',1,9,NULL,3)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Ma krótko przystrzyżone ciemne włosy i ziemistą skórę. Jest potężny i mocno umięśniony. Wygląda groźne.',2,9,NULL,3)
		--stary
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Nosi plemienne ubrania wykończone futrem. Jest krępa i przygarbiona. Ma ciemnoszarą skórę i pożółkłe ze starości kły.',1,9,NULL,4)
INSERT [dbo].[Wyglad] ([wyglad], [plecID],[rasaID], [podrasaID], [wiekID]) VALUES (N'Jest wielki, ale część z jego mięśni już zanikła. Ma ułamany kieł i głęboką bliznę nad lewym okiem.',2,9,NULL,4)

--tabela Osobowość


